import 'package:fuzzywuzzy/fuzzywuzzy.dart';

class Fuzzywuzzy {
  static String searchForExercise(String query) {
    final result = extractOne(
      query: query,
      choices: exerciseKeywords,
      cutoff: 70,
    );

    return result.choice;
  }

  static const List<String> exerciseKeywords = [
    "180",
    "3/4",
    "3/4 sit-up",
    "360",
    "45°",
    "45° leg",
    "45° side",
    "45в°",
    "45в° calf",
    "45в° leg",
    "abdominal",
    "abdominal fallout",
    "abduction",
    "abductor",
    "above",
    "above head",
    "across",
    "across face",
    "adduction",
    "adduction male",
    "adductor",
    "adductor stretch",
    "advanced",
    "advanced windmill",
    "against",
    "against wall",
    "air",
    "air bike",
    "all",
    "all fours",
    "alternate",
    "alternate biceps",
    "alternate extension",
    "alternate front",
    "alternate hammer",
    "alternate heel",
    "alternate kickback",
    "alternate lateral",
    "alternate leg",
    "alternate overhead",
    "alternate preacher",
    "alternate press",
    "alternate raise",
    "alternate row",
    "alternate seated",
    "alternate shoulder",
    "alternate side",
    "alternate triceps",
    "alternating",
    "alternating arm",
    "alternating bicep",
    "alternating biceps",
    "alternating hang",
    "alternating narrow",
    "alternating press",
    "alternating renegade",
    "alternating row",
    "alternating seated",
    "alternating tricep",
    "alternating v-up",
    "angle",
    "angle pose",
    "angled",
    "angled calf",
    "ankle",
    "ankle circles",
    "ankles",
    "anti",
    "anti gravity",
    "apart",
    "apart circular",
    "archer",
    "archer pull",
    "archer push",
    "arm",
    "arm against",
    "arm alternate",
    "arm bench",
    "arm bent",
    "arm bent-over",
    "arm bicep",
    "arm blaster",
    "arm chest",
    "arm chin-up",
    "arm clean",
    "arm concentration",
    "arm curl",
    "arm decline",
    "arm deltoid",
    "arm dip",
    "arm extension",
    "arm floor",
    "arm fly",
    "arm french",
    "arm hammer",
    "arm incline",
    "arm jerk",
    "arm kickback",
    "arm lateral",
    "arm military",
    "arm neutral",
    "arm overhead",
    "arm palm",
    "arm preacher",
    "arm press",
    "arm pronated",
    "arm prone",
    "arm pulldown",
    "arm pullover",
    "arm push",
    "arm push-up",
    "arm rear",
    "arm reverse",
    "arm rotate",
    "arm row",
    "arm seated",
    "arm shoulder",
    "arm side",
    "arm single",
    "arm slam",
    "arm slingers",
    "arm snatch",
    "arm standing",
    "arm straight",
    "arm supinated",
    "arm towel",
    "arm tricep",
    "arm triceps",
    "arm twisting",
    "arm upright",
    "arm ups",
    "arm wrist",
    "arm zottman",
    "arms",
    "arms apart",
    "arms chest",
    "arms extended",
    "arms overhead",
    "arms pullover",
    "arms straight",
    "arnold",
    "arnold press",
    "around",
    "around pullover",
    "around world",
    "assisted",
    "assisted chest",
    "assisted chin-up",
    "assisted hanging",
    "assisted inverse",
    "assisted lying",
    "assisted motion",
    "assisted parallel",
    "assisted prone",
    "assisted pull-up",
    "assisted seated",
    "assisted side",
    "assisted sit-up",
    "assisted standing",
    "assisted triceps",
    "assisted wheel",
    "assisted wide-grip",
    "astride",
    "astride jumps",
    "attachment",
    "back",
    "back close",
    "back curl",
    "back extension",
    "back forth",
    "back head",
    "back high",
    "back lever",
    "back pec",
    "back pov",
    "back row",
    "back seated",
    "back shrug",
    "back stiff",
    "back stretch",
    "back underhand",
    "back wrist",
    "backward",
    "backward jump",
    "balance",
    "balance bicep",
    "balance board",
    "ball",
    "ball alternating",
    "ball back",
    "ball between",
    "ball catch",
    "ball chest",
    "ball close",
    "ball crunch",
    "ball dip",
    "ball hip",
    "ball hug",
    "ball lat",
    "ball leg",
    "ball lower",
    "ball lying",
    "ball one",
    "ball overhead",
    "ball pike",
    "ball prone",
    "ball seated",
    "ball supine",
    "ball wall",
    "ball,",
    "ball, arms",
    "band",
    "band alternating",
    "band assisted",
    "band bench",
    "band bent-over",
    "band bicycle",
    "band close-grip",
    "band concentration",
    "band fixed",
    "band front",
    "band hip",
    "band horizontal",
    "band jack",
    "band kneeling",
    "band leg",
    "band lying",
    "band one",
    "band pull",
    "band push",
    "band reverse",
    "band seated",
    "band shoulder",
    "band shrug",
    "band side",
    "band single",
    "band squat",
    "band standing",
    "band step-up",
    "band stiff",
    "band straight",
    "band twisting",
    "band two",
    "band under",
    "band underhand",
    "band v-up",
    "band vertical",
    "band wrist",
    "band y-raise",
    "bar",
    "bar deadlift",
    "bar dip",
    "bar french",
    "bar lateral",
    "bar lying",
    "bar reverse",
    "bar row",
    "bar seated",
    "bar squat",
    "bar standing",
    "barbell",
    "barbell alternate",
    "barbell anti",
    "barbell bench",
    "barbell bent",
    "barbell biceps",
    "barbell clean",
    "barbell clean-grip",
    "barbell close",
    "barbell close-grip",
    "barbell curl",
    "barbell deadlift",
    "barbell decline",
    "barbell drag",
    "barbell floor",
    "barbell front",
    "barbell full",
    "barbell glute",
    "barbell good",
    "barbell guillotine",
    "barbell hack",
    "barbell hammer",
    "barbell high",
    "barbell incline",
    "barbell jefferson",
    "barbell jump",
    "barbell lateral",
    "barbell low",
    "barbell lunge",
    "barbell lying",
    "barbell narrow",
    "barbell one",
    "barbell overhead",
    "barbell palms",
    "barbell pendlay",
    "barbell pin",
    "barbell preacher",
    "barbell press",
    "barbell prone",
    "barbell pullover",
    "barbell rack",
    "barbell rear",
    "barbell revers",
    "barbell reverse",
    "barbell rollerout",
    "barbell romanian",
    "barbell seated",
    "barbell shrug",
    "barbell side",
    "barbell single",
    "barbell sitted",
    "barbell skier",
    "barbell speed",
    "barbell spider",
    "barbell split",
    "barbell squat",
    "barbell standing",
    "barbell step-up",
    "barbell stiff",
    "barbell straight",
    "barbell sumo",
    "barbell thruster",
    "barbell triceps",
    "barbell upright",
    "barbell wide",
    "barbell wide-grip",
    "barbell wrist",
    "barbell zercher",
    "bars",
    "basic",
    "basic toe",
    "battling",
    "battling ropes",
    "bear",
    "bear crawl",
    "behind",
    "behind head",
    "behind neck",
    "bench",
    "bench dip",
    "bench dips",
    "bench extension",
    "bench fly",
    "bench front",
    "bench hip",
    "bench leg",
    "bench male",
    "bench neutral",
    "bench one",
    "bench press",
    "bench pull-ups",
    "bench revers",
    "bench row",
    "bench seated",
    "bench squat",
    "bench support",
    "bench two",
    "bench wrist",
    "benches",
    "bend",
    "bend crunch",
    "bend stability",
    "bends",
    "bends male",
    "bent",
    "bent arm",
    "bent arms",
    "bent knee",
    "bent knees",
    "bent over",
    "bent press",
    "bent-over",
    "bent-over hip",
    "bent-over row",
    "between",
    "between ankles",
    "between benches",
    "between knees",
    "bicep",
    "bicep curl",
    "biceps",
    "biceps curl",
    "biceps leg",
    "biceps narrow",
    "biceps pull-up",
    "bicycle",
    "bicycle crunch",
    "big",
    "big toe",
    "bike",
    "bike run",
    "bike walk",
    "blaster",
    "board",
    "body",
    "body crunch",
    "body hammer",
    "body rotation",
    "body saw",
    "body-up",
    "bodyweight",
    "bodyweight drop",
    "bodyweight incline",
    "bodyweight kneeling",
    "bodyweight side",
    "bodyweight squatting",
    "bodyweight standing",
    "bosu",
    "bosu ball",
    "both",
    "both legs",
    "bottoms",
    "bottoms clean",
    "bottoms-up",
    "bowling",
    "bowling motion",
    "box",
    "box jump",
    "boxing",
    "bradford",
    "bradford press",
    "bradford rocky",
    "breeding",
    "bridge",
    "bridge floor",
    "bridge hip",
    "bridge march",
    "bridge mountain",
    "bridge outstretched",
    "bridge two",
    "bug",
    "burpee",
    "butt-ups",
    "butterfly",
    "butterfly yoga",
    "cable",
    "cable alternate",
    "cable assisted",
    "cable bar",
    "cable bench",
    "cable close",
    "cable concentration",
    "cable cross-over",
    "cable curl",
    "cable deadlift",
    "cable decline",
    "cable drag",
    "cable floor",
    "cable forward",
    "cable front",
    "cable hammer",
    "cable high",
    "cable hip",
    "cable incline",
    "cable judo",
    "cable kickback",
    "cable kneeling",
    "cable lat",
    "cable lateral",
    "cable low",
    "cable lying",
    "cable machine",
    "cable middle",
    "cable one",
    "cable overhead",
    "cable palm",
    "cable preacher",
    "cable press",
    "cable pull",
    "cable pulldown",
    "cable pushdown",
    "cable rear",
    "cable reverse",
    "cable reverse-grip",
    "cable rope",
    "cable russian",
    "cable seated",
    "cable shoulder",
    "cable shrug",
    "cable side",
    "cable squat",
    "cable squatting",
    "cable standing",
    "cable straight",
    "cable supine",
    "cable thibaudeau",
    "cable triceps",
    "cable tuck",
    "cable twist",
    "cable twisting",
    "cable two",
    "cable underhand",
    "cable upper",
    "cable upright",
    "cable wide",
    "cable wrist",
    "cage",
    "calf",
    "calf press",
    "calf push",
    "calf raise",
    "calf raises",
    "calf stretch",
    "calves",
    "calves calf",
    "calves stretch",
    "cambered",
    "cambered bar",
    "can",
    "can lateral",
    "captains",
    "captains chair",
    "carry",
    "caster",
    "cat",
    "catch",
    "catch overhead",
    "chair",
    "chair leg",
    "chair squat",
    "chair straight",
    "chest",
    "chest crossovers",
    "chest dip",
    "chest fly",
    "chest front",
    "chest pad",
    "chest pass",
    "chest press",
    "chest push",
    "chest squat",
    "chest squeeze",
    "chest stretch",
    "chest tap",
    "chest throw",
    "chin",
    "chin-up",
    "chin-up dip",
    "chin-ups",
    "chin-ups narrow",
    "circles",
    "circles knee",
    "circular",
    "circular toe",
    "clap",
    "clap push",
    "clasped",
    "clasped circular",
    "clean",
    "clean from",
    "clean grip",
    "clean jerk",
    "clean press",
    "clean-grip",
    "clean-grip front",
    "climb",
    "climber",
    "climber cross",
    "clock",
    "clock push-up",
    "close",
    "close grip",
    "close-grip",
    "close-grip bench",
    "close-grip concentration",
    "close-grip curl",
    "close-grip off",
    "close-grip one",
    "close-grip press",
    "close-grip pulldown",
    "close-grip push-up",
    "close-grip row",
    "close-grip triceps",
    "closer",
    "closer hack",
    "cocoons",
    "concentration",
    "concentration curl",
    "concentration extension",
    "contralateral",
    "contralateral forward",
    "cossack",
    "cossack squats",
    "crab",
    "crab twist",
    "crawl",
    "crawl push",
    "cross",
    "cross body",
    "cross stretch",
    "cross trainer",
    "cross-over",
    "cross-over high",
    "cross-over lateral",
    "cross-over revers",
    "cross-over variation",
    "crossover",
    "crossover seated",
    "crossovers",
    "crunch",
    "crunch bosu",
    "crunch chest",
    "crunch floor",
    "crunch full",
    "crunch hands",
    "crunch rope",
    "crunch stability",
    "crunch wall",
    "crunches",
    "crunches floor",
    "crusher",
    "cuban",
    "cuban press",
    "curl",
    "curl arm",
    "curl bench",
    "curl exercise",
    "curl floor",
    "curl incline",
    "curl leg",
    "curl lunge",
    "curl over",
    "curl press",
    "curl pull-up",
    "curl reverse",
    "curl rope",
    "curl shoulder",
    "curl sit",
    "curl squat",
    "curl stability",
    "curl stork",
    "curl-up",
    "curls",
    "curls arm",
    "curtsey",
    "curtsey squat",
    "cycle",
    "cycle cross",
    "dead",
    "dead bug",
    "deadlift",
    "deadlift stepbox",
    "decline",
    "decline bench",
    "decline bent",
    "decline bridge",
    "decline chest",
    "decline close",
    "decline crunch",
    "decline fly",
    "decline hammer",
    "decline one",
    "decline press",
    "decline pullover",
    "decline push-up",
    "decline reverse-grip",
    "decline seated",
    "decline shrug",
    "decline sit-up",
    "decline triceps",
    "decline twist",
    "decline wide-grip",
    "deep",
    "deep push",
    "degrees",
    "degrees one",
    "delt",
    "delt raise",
    "delt row",
    "delt row_shoulder",
    "deltoid",
    "deltoid rear",
    "deltoid stretch",
    "depresor",
    "depresor retractor",
    "depth",
    "depth jump",
    "diagonal",
    "diagonal kick",
    "diamond",
    "diamond push-up",
    "dip",
    "dip bench",
    "dip between",
    "dip cage",
    "dip dip-pull-up",
    "dip floor",
    "dip high",
    "dip kneeling",
    "dip knees",
    "dip straight",
    "dip-pull-up",
    "dip-pull-up cage",
    "dips",
    "dips floor",
    "dog",
    "donkey",
    "donkey calf",
    "double",
    "double alternating",
    "double jerk",
    "double push",
    "double snatch",
    "double windmill",
    "down",
    "down one",
    "down wrist",
    "drag",
    "drag curl",
    "drive",
    "drop",
    "drop jump",
    "drop push",
    "dumbbell",
    "dumbbell alternate",
    "dumbbell alternating",
    "dumbbell arnold",
    "dumbbell around",
    "dumbbell bench",
    "dumbbell bent",
    "dumbbell bicep",
    "dumbbell biceps",
    "dumbbell burpee",
    "dumbbell clean",
    "dumbbell close",
    "dumbbell close-grip",
    "dumbbell concentration",
    "dumbbell contralateral",
    "dumbbell cross",
    "dumbbell cuban",
    "dumbbell deadlift",
    "dumbbell decline",
    "dumbbell finger",
    "dumbbell fly",
    "dumbbell forward",
    "dumbbell front",
    "dumbbell full",
    "dumbbell goblet",
    "dumbbell hammer",
    "dumbbell high",
    "dumbbell incline",
    "dumbbell iron",
    "dumbbell kickback",
    "dumbbell kickbacks",
    "dumbbell kneeling",
    "dumbbell lateral",
    "dumbbell lunge",
    "dumbbell lying",
    "dumbbell neutral",
    "dumbbell one",
    "dumbbell over",
    "dumbbell palm",
    "dumbbell palms",
    "dumbbell peacher",
    "dumbbell plyo",
    "dumbbell preacher",
    "dumbbell press",
    "dumbbell pronate-grip",
    "dumbbell prone",
    "dumbbell pullover",
    "dumbbell push",
    "dumbbell raise",
    "dumbbell rear",
    "dumbbell revers",
    "dumbbell reverse",
    "dumbbell romanian",
    "dumbbell rotation",
    "dumbbell scott",
    "dumbbell seated",
    "dumbbell shrug",
    "dumbbell side",
    "dumbbell single",
    "dumbbell squat",
    "dumbbell standing",
    "dumbbell step",
    "dumbbell step-up",
    "dumbbell stiff",
    "dumbbell straight",
    "dumbbell sumo",
    "dumbbell supported",
    "dumbbell tate",
    "dumbbell tricep",
    "dumbbell twisting",
    "dumbbell upright",
    "dumbbell w-press",
    "dumbbell waiter",
    "dumbbell zottman",
    "dumbbells",
    "dumbbells seated",
    "dynamic",
    "dynamic chest",
    "elbow",
    "elbow dips",
    "elbow knee",
    "elbow lift",
    "elbow press",
    "elbow-to-knee",
    "elevated",
    "elevated seated",
    "elevator",
    "elliptical",
    "elliptical cross",
    "equipment",
    "ergometer",
    "exercise",
    "exercise ball",
    "extended",
    "extended range",
    "extended stretch",
    "extension",
    "extension across",
    "extension arms",
    "extension behind",
    "extension bench",
    "extension exercise",
    "extension hands",
    "extension incline",
    "extension knee",
    "extension knees",
    "extension pullover",
    "extension rope",
    "extension rotation",
    "extension skull",
    "extension stability",
    "extension towel",
    "external",
    "external rotation",
    "external shoulder",
    "ez-bar",
    "ez-bar biceps",
    "ez-bar close-grip",
    "ez-barbell",
    "ez-barbell standing",
    "face",
    "face press",
    "facing",
    "facing dog",
    "fallout",
    "farmers",
    "farmers walk",
    "feet",
    "female",
    "femoral",
    "femoris",
    "femoris stretch",
    "figure",
    "finger",
    "finger curls",
    "fixed",
    "fixed back",
    "flag",
    "flat",
    "flat bench",
    "flexion",
    "flexion leg",
    "flexor",
    "flexor depresor",
    "flexor quad",
    "flexor stretch",
    "flip",
    "floor",
    "floor calf",
    "floor fly",
    "floor press",
    "floor rear",
    "floor seated",
    "floor stretch",
    "floor tricep",
    "flutter",
    "flutter kicks",
    "fly",
    "fly barbell",
    "fly exercise",
    "fly parallel",
    "fly stability",
    "fly support",
    "flyes",
    "forth",
    "forth step",
    "forward",
    "forward angled",
    "forward jump",
    "forward lunge",
    "forward raise",
    "fours",
    "fours squad",
    "frankenstein",
    "frankenstein squat",
    "french",
    "french press",
    "frog",
    "frog crunch",
    "frog planche",
    "frog stretch",
    "from",
    "from bench",
    "from hang",
    "from point",
    "front",
    "front chest",
    "front lateral",
    "front lever",
    "front plank",
    "front pulldown",
    "front raise",
    "front shoulder",
    "front squat",
    "full",
    "full can",
    "full maltese",
    "full planche",
    "full range",
    "full sit-up",
    "full squat",
    "full zercher",
    "get",
    "get squat",
    "gironda",
    "gironda sternum",
    "glute",
    "glute bridge",
    "glute stretch",
    "glute-ham",
    "glute-ham raise",
    "glutes",
    "glutes stretch",
    "gluteus",
    "gluteus piriformis",
    "goblet",
    "goblet squat",
    "good",
    "good morning",
    "gorilla",
    "gorilla chin",
    "gravity",
    "gravity press",
    "greatest",
    "greatest stretch",
    "grip",
    "grip behind",
    "grip bench",
    "grip bent",
    "grip biceps",
    "grip chin-up",
    "grip concentration",
    "grip curl",
    "grip decline",
    "grip face",
    "grip incline",
    "grip lat",
    "grip lateral",
    "grip machine",
    "grip military",
    "grip one",
    "grip preacher",
    "grip press",
    "grip pull-up",
    "grip pulldown",
    "grip push",
    "grip push-up",
    "grip rear",
    "grip row",
    "grip seated",
    "grip skull",
    "grip skullcrusher",
    "grip triceps",
    "grip vertical",
    "gripless",
    "gripless shrug",
    "gripper",
    "gripper hands",
    "groin",
    "groin crunch",
    "ground",
    "guillotine",
    "guillotine bench",
    "hack",
    "hack calf",
    "hack one",
    "hack squat",
    "half",
    "half knee",
    "half sit-up",
    "hammer",
    "hammer curl",
    "hammer curls",
    "hammer grip",
    "hammer preacher",
    "hammer press",
    "hamstring",
    "hamstring calf",
    "hamstring curl",
    "hamstring stretch",
    "hand",
    "hand pull",
    "hand push",
    "hand raise",
    "hand squeeze",
    "handle",
    "handle parallel",
    "hands",
    "hands against",
    "hands behind",
    "hands bike",
    "hands clasped",
    "hands overhead",
    "hands reversed",
    "handstand",
    "handstand push-up",
    "hang",
    "hang clean",
    "hang position",
    "hanging",
    "hanging bent",
    "hanging knee",
    "hanging leg",
    "hanging leg-hip",
    "hanging oblique",
    "hanging pike",
    "hanging straight",
    "head",
    "head chest",
    "head military",
    "head tricep",
    "heel",
    "heel touchers",
    "high",
    "high bar",
    "high curl",
    "high knee",
    "high knees",
    "high parallel",
    "high pull",
    "high pulley",
    "high reverse",
    "high row",
    "hindu",
    "hindu push-up",
    "hip",
    "hip abduction",
    "hip abductor",
    "hip adduction",
    "hip extension",
    "hip flexor",
    "hip internal",
    "hip lat",
    "hip lift",
    "hip parallel",
    "hip raise",
    "hip stretch",
    "hip thrusts",
    "hook.",
    "hook. boxing",
    "hops",
    "horizontal",
    "horizontal one",
    "horizontal pallof",
    "hug",
    "hug keens",
    "hyght",
    "hyght dumbbell",
    "hyper",
    "hyper extension",
    "hyper flat",
    "hyperextension",
    "hyperextension bench",
    "hyperextension stability",
    "impossible",
    "impossible dips",
    "inchworm",
    "incline",
    "incline alternate",
    "incline bench",
    "incline biceps",
    "incline breeding",
    "incline chest",
    "incline close",
    "incline close-grip",
    "incline curl",
    "incline fly",
    "incline hammer",
    "incline inner",
    "incline leg",
    "incline one",
    "incline palm-in",
    "incline press",
    "incline push",
    "incline push-up",
    "incline pushdown",
    "incline raise",
    "incline rear",
    "incline reverse",
    "incline reverse-grip",
    "incline row",
    "incline scapula",
    "incline shoulder",
    "incline shrug",
    "incline side",
    "incline t-raise",
    "incline treadmill",
    "incline tricep",
    "incline triceps",
    "incline twisted",
    "incline twisting",
    "incline two",
    "incline y-raise",
    "inner",
    "inner biceps",
    "inner chest",
    "inner curl",
    "inside",
    "inside leg",
    "intermediate",
    "intermediate hip",
    "internal",
    "internal rotation",
    "into",
    "into bridge",
    "inverse",
    "inverse leg",
    "inverted",
    "inverted row",
    "iron",
    "iron cross",
    "isometric",
    "isometric chest",
    "isometric wipers",
    "jack",
    "jack burpee",
    "jack jump",
    "jack knife",
    "jackknife",
    "jackknife sit-up",
    "janda",
    "janda sit-up",
    "jefferson",
    "jefferson squat",
    "jerk",
    "judo",
    "judo flip",
    "jump",
    "jump down",
    "jump male",
    "jump rope",
    "jump squat",
    "jump step",
    "jumps",
    "jumps male",
    "kayak",
    "kayak row",
    "keens",
    "keens chest",
    "kettlebell",
    "kettlebell advanced",
    "kettlebell alternating",
    "kettlebell arnold",
    "kettlebell bent",
    "kettlebell bottoms",
    "kettlebell double",
    "kettlebell extended",
    "kettlebell figure",
    "kettlebell front",
    "kettlebell goblet",
    "kettlebell hang",
    "kettlebell lunge",
    "kettlebell one",
    "kettlebell pirate",
    "kettlebell pistol",
    "kettlebell plyo",
    "kettlebell seated",
    "kettlebell seesaw",
    "kettlebell sumo",
    "kettlebell swing",
    "kettlebell thruster",
    "kettlebell turkish",
    "kettlebell two",
    "kettlebell windmill",
    "kick",
    "kick hamstring",
    "kick out",
    "kick push-up",
    "kickback",
    "kickback stork",
    "kickbacks",
    "kickbacks exercise",
    "kicks",
    "kicks male",
    "kipping",
    "kipping muscle",
    "knee",
    "knee against",
    "knee bends",
    "knee good",
    "knee legs",
    "knee lying",
    "knee raise",
    "knee stretch",
    "knee touch",
    "kneeling",
    "kneeling bicep",
    "kneeling crunch",
    "kneeling jump",
    "kneeling lat",
    "kneeling leg",
    "kneeling one",
    "kneeling plank",
    "kneeling push-up",
    "kneeling rear",
    "kneeling step",
    "kneeling triceps",
    "kneeling twist",
    "kneeling twisting",
    "knees",
    "knees bent",
    "knees female",
    "knees lunge",
    "knees off",
    "knife",
    "knife sit-up",
    "korean",
    "korean dips",
    "l-pull-up",
    "l-sit",
    "l-sit floor",
    "landmine",
    "landmine 180",
    "landmine lateral",
    "lat",
    "lat bar",
    "lat pulldown",
    "lat stretch",
    "lateral",
    "lateral bent-over",
    "lateral front",
    "lateral high",
    "lateral lunge",
    "lateral pulldown",
    "lateral raise",
    "lateral stretch",
    "lateral throw",
    "lateral wide",
    "lean",
    "lean planche",
    "left",
    "left hook.",
    "leg",
    "leg balance",
    "leg bridge",
    "leg calf",
    "leg concentration",
    "leg curl",
    "leg deadlift",
    "leg donkey",
    "leg extended",
    "leg extension",
    "leg floor",
    "leg fly",
    "leg good",
    "leg hamstring",
    "leg hip",
    "leg kick",
    "leg lift",
    "leg outer",
    "leg platform",
    "leg press",
    "leg prone",
    "leg pull",
    "leg raise",
    "leg raised",
    "leg reverse",
    "leg shoulder",
    "leg sit",
    "leg split",
    "leg squat",
    "leg stabilization",
    "leg straight",
    "leg wide",
    "leg-hip",
    "leg-hip raise",
    "legged",
    "legged diagonal",
    "legs",
    "legs bench",
    "legs calf",
    "lever",
    "lever alternate",
    "lever alternating",
    "lever assisted",
    "lever back",
    "lever bar",
    "lever bent",
    "lever bent-over",
    "lever bicep",
    "lever calf",
    "lever chest",
    "lever deadlift",
    "lever decline",
    "lever donkey",
    "lever front",
    "lever gripless",
    "lever gripper",
    "lever hammer",
    "lever high",
    "lever hip",
    "lever horizontal",
    "lever incline",
    "lever kneeling",
    "lever lateral",
    "lever leg",
    "lever lying",
    "lever military",
    "lever narrow",
    "lever one",
    "lever overhand",
    "lever preacher",
    "lever pullover",
    "lever reps",
    "lever reverse",
    "lever rotary",
    "lever seated",
    "lever shoulder",
    "lever shrug",
    "lever standing",
    "lever t-bar",
    "lever triceps",
    "lever unilateral",
    "lift",
    "lift reverse",
    "lifting",
    "lifting hip",
    "london",
    "london bridge",
    "low",
    "low bar",
    "low fly",
    "low glute",
    "low row",
    "low seated",
    "lower",
    "lower arms",
    "lower back",
    "lower body",
    "lunge",
    "lunge bicep",
    "lunge bowling",
    "lunge jump",
    "lunge male",
    "lunge pass",
    "lunge swing",
    "lunge triceps",
    "lunge twist",
    "lying",
    "lying adductor",
    "lying alternate",
    "lying back",
    "lying bent",
    "lying bicep",
    "lying biceps",
    "lying calf",
    "lying calves",
    "lying close",
    "lying close-grip",
    "lying elbow",
    "lying extension",
    "lying external",
    "lying femoral",
    "lying floor",
    "lying fly",
    "lying glutes",
    "lying gluteus",
    "lying hammer",
    "lying hip",
    "lying leg",
    "lying leg-hip",
    "lying lifting",
    "lying one",
    "lying preacher",
    "lying pronation",
    "lying pullover",
    "lying quads",
    "lying rear",
    "lying row",
    "lying side",
    "lying single",
    "lying squat",
    "lying straight",
    "lying supination",
    "lying supine",
    "lying triceps",
    "lying twist",
    "lying two-one",
    "lying wide",
    "machine",
    "machine bicep",
    "machine decline",
    "machine incline",
    "machine inner",
    "machine lat",
    "machine reverse",
    "major",
    "major stretch",
    "male",
    "maltese",
    "march",
    "march sit",
    "medicine",
    "medicine ball",
    "middle",
    "middle fly",
    "military",
    "military press",
    "mixed",
    "mixed grip",
    "modified",
    "modified hindu",
    "modified push",
    "monster",
    "monster walk",
    "morning",
    "motion",
    "motion russian",
    "mountain",
    "mountain climber",
    "multiple",
    "multiple response",
    "muscle",
    "muscle bar",
    "muscle-up",
    "muscle-up vertical",
    "narrow",
    "narrow grip",
    "narrow parallel",
    "narrow pull-ups",
    "narrow push-up",
    "narrow row",
    "narrow stance",
    "neck",
    "neck press",
    "neck side",
    "neck stretch",
    "neck triceps",
    "negative",
    "negative crunch",
    "neutral",
    "neutral grip",
    "neutral wrist",
    "oblique",
    "oblique crunch",
    "oblique crunches",
    "oblique knee",
    "off",
    "off dumbbell",
    "off ground",
    "olympic",
    "olympic barbell",
    "one",
    "one arm",
    "one hand",
    "one leg",
    "one legged",
    "otis",
    "out",
    "out sit",
    "outer",
    "outer hip",
    "outside",
    "outside leg",
    "outstretched",
    "outstretched leg",
    "over",
    "over alternate",
    "over bench",
    "over exercise",
    "over head",
    "over incline",
    "over one",
    "over row",
    "over triceps",
    "over two",
    "overhand",
    "overhand triceps",
    "overhead",
    "overhead biceps",
    "overhead carry",
    "overhead crunch",
    "overhead curl",
    "overhead full",
    "overhead press",
    "overhead reach",
    "overhead slam",
    "overhead squat",
    "overhead throw",
    "overhead tricep",
    "overhead triceps",
    "pad",
    "pallof",
    "pallof press",
    "palm",
    "palm press",
    "palm rotational",
    "palm-in",
    "palm-in press",
    "palms",
    "palms down",
    "palms incline",
    "palms press",
    "palms wrist",
    "parallel",
    "parallel bars",
    "parallel close",
    "parallel grip",
    "pass",
    "pass through",
    "peacher",
    "peacher hammer",
    "pec",
    "pec stretch",
    "pectoralis",
    "pectoralis major",
    "pelvic",
    "pelvic tilt",
    "pendlay",
    "pendlay row",
    "peroneals",
    "peroneals stretch",
    "pike",
    "pike push",
    "pike-to-cobra",
    "pike-to-cobra push-up",
    "pin",
    "pin presses",
    "pirate",
    "pirate supper",
    "piriformis",
    "piriformis stretch",
    "pistol",
    "pistol male",
    "pistol squat",
    "planche",
    "planche push-up",
    "plank",
    "plank hip",
    "plank leg",
    "plank rear",
    "plank tap",
    "plank twist",
    "platform",
    "platform slide",
    "plus",
    "plyo",
    "plyo push",
    "plyo push-up",
    "plyo squat",
    "point",
    "point plank",
    "point stance",
    "pose",
    "pose rope",
    "pose sequence",
    "position",
    "posterior",
    "posterior step",
    "posterior tibialis",
    "potty",
    "potty squat",
    "pov",
    "power",
    "power clean",
    "power point",
    "preacher",
    "preacher curl",
    "press",
    "press back",
    "press exercise",
    "press floor",
    "press leg",
    "press machine",
    "press parallel",
    "press side",
    "press sit-up",
    "presses",
    "prisoner",
    "prisoner half",
    "pro",
    "pro lat",
    "pronate-grip",
    "pronate-grip triceps",
    "pronated",
    "pronated triceps",
    "pronation",
    "pronation floor",
    "prone",
    "prone curl",
    "prone hammer",
    "prone hamstring",
    "prone incline",
    "prone leg",
    "prone lower",
    "prone lying",
    "prone rectus",
    "prone twist",
    "pull",
    "pull bodyweight",
    "pull flat",
    "pull neutral",
    "pull stretch",
    "pull through",
    "pull-in",
    "pull-in stability",
    "pull-up",
    "pull-up cable",
    "pull-up pulldown",
    "pull-ups",
    "pulldown",
    "pulldown behind",
    "pulldown bicep",
    "pulldown full",
    "pulldown pro",
    "pulldown rope",
    "pulldown v-bar",
    "pulley",
    "pulley overhead",
    "pullover",
    "pullover exercise",
    "pullover hip",
    "pullover press",
    "pullover rope",
    "push",
    "push bosu",
    "push depth",
    "push from",
    "push lower",
    "push multiple",
    "push neck",
    "push press",
    "push pull",
    "push run",
    "push single",
    "push sit-up",
    "push stretch",
    "push-up",
    "push-up bosu",
    "push-up box",
    "push-up close-grip",
    "push-up exercise",
    "push-up inside",
    "push-up knees",
    "push-up lower",
    "push-up male",
    "push-up medicine",
    "push-up plus",
    "push-up side",
    "push-up stability",
    "push-up wall",
    "pushdown",
    "pushdown rope",
    "pushdown straight",
    "pushdown sz-bar",
    "pushdown v-bar",
    "pyramid",
    "quad",
    "quad stretch",
    "quads",
    "quads stretch",
    "quarter",
    "quarter sit-up",
    "quick",
    "quick feet",
    "rack",
    "rack pull",
    "raise",
    "raise above",
    "raise band",
    "raise bent",
    "raise crunch",
    "raise dumbbell",
    "raise female",
    "raise flat",
    "raise hammer",
    "raise lateral",
    "raise leg",
    "raise over",
    "raise palm",
    "raise parallel",
    "raise pullover",
    "raise single",
    "raise staircase",
    "raise support",
    "raise tennis",
    "raise throw",
    "raised",
    "raised exercise",
    "raises",
    "range",
    "range hands",
    "range motion",
    "range one",
    "reach",
    "reach twist",
    "rear",
    "rear decline",
    "rear delt",
    "rear deltoid",
    "rear drive",
    "rear fly",
    "rear lateral",
    "rear lunge",
    "rear pull-up",
    "rear pulldown",
    "reclining",
    "reclining big",
    "rectus",
    "rectus femoris",
    "release",
    "renegade",
    "renegade row",
    "reps",
    "resistance",
    "resistance band",
    "response",
    "retractor",
    "revers",
    "revers fly",
    "revers grip",
    "revers wrist",
    "reverse",
    "reverse bench",
    "reverse calf",
    "reverse close-grip",
    "reverse crunch",
    "reverse curl",
    "reverse decline",
    "reverse dip",
    "reverse fly",
    "reverse grip",
    "reverse hyper",
    "reverse hyperextension",
    "reverse one",
    "reverse plank",
    "reverse preacher",
    "reverse push-up",
    "reverse spider",
    "reverse t-bar",
    "reverse wrist",
    "reverse-grip",
    "reverse-grip press",
    "reverse-grip pushdown",
    "reverse-grip straight",
    "reversed",
    "reversed clasped",
    "ring",
    "ring dips",
    "rocking",
    "rocking frog",
    "rocking leg",
    "rocky",
    "rocky press",
    "rocky pull-up",
    "roller",
    "roller back",
    "roller body",
    "roller hip",
    "roller reverse",
    "roller seated",
    "roller side",
    "rollerer",
    "rollerout",
    "rollerout from",
    "romanian",
    "romanian deadlift",
    "rope",
    "rope attachment",
    "rope climb",
    "rope crossover",
    "rope elevated",
    "rope extension",
    "rope hammer",
    "rope high",
    "rope incline",
    "rope lying",
    "rope male",
    "rope one",
    "rope seated",
    "ropes",
    "rotary",
    "rotary calf",
    "rotate",
    "rotation",
    "rotation reverse",
    "rotational",
    "rotational bent",
    "rotational row",
    "round",
    "round arm",
    "row",
    "row back",
    "row bench",
    "row bent",
    "row female",
    "row kneeling",
    "row rope",
    "row stirrups",
    "row straps",
    "row towel",
    "row v-bar",
    "row_shoulder",
    "run",
    "run equipment",
    "run release",
    "runners",
    "runners stretch",
    "russian",
    "russian twist",
    "russian twists",
    "saw",
    "scapula",
    "scapula dips",
    "scapula push",
    "scapula push-up",
    "scapular",
    "scapular pull-up",
    "scissor",
    "scissor jumps",
    "scott",
    "scott press",
    "seated",
    "seated alternate",
    "seated behind",
    "seated bench",
    "seated bent",
    "seated bicep",
    "seated biceps",
    "seated bradford",
    "seated calf",
    "seated chest",
    "seated close",
    "seated close-grip",
    "seated crunch",
    "seated curl",
    "seated curls",
    "seated dip",
    "seated fly",
    "seated front",
    "seated glute",
    "seated good",
    "seated hammer",
    "seated hamstring",
    "seated high",
    "seated hip",
    "seated inner",
    "seated kickback",
    "seated lateral",
    "seated leg",
    "seated lower",
    "seated neutral",
    "seated one",
    "seated overhead",
    "seated palms",
    "seated pectoralis",
    "seated piriformis",
    "seated preacher",
    "seated press",
    "seated rear",
    "seated revers",
    "seated reverse",
    "seated row",
    "seated shoulder",
    "seated side",
    "seated single",
    "seated squat",
    "seated straight",
    "seated triceps",
    "seated twist",
    "seated two",
    "seated wide",
    "seated wide-grip",
    "seated wrist",
    "seesaw",
    "seesaw press",
    "self",
    "self assisted",
    "semi",
    "semi squat",
    "sequence",
    "short",
    "short stride",
    "shoulder",
    "shoulder external",
    "shoulder flexor",
    "shoulder grip",
    "shoulder internal",
    "shoulder male",
    "shoulder press",
    "shoulder raise",
    "shoulder raises",
    "shoulder rotation",
    "shoulder stretch",
    "shoulder tap",
    "shrug",
    "side",
    "side bend",
    "side bent",
    "side bridge",
    "side crunch",
    "side deadlift",
    "side hip",
    "side lat",
    "side lying",
    "side plank",
    "side pov",
    "side press",
    "side push",
    "side push-up",
    "side quads",
    "side split",
    "side stretch",
    "side triceps",
    "side wrist",
    "side-to-side",
    "side-to-side chin",
    "side-to-side toe",
    "single",
    "single arm",
    "single extension",
    "single leg",
    "single response",
    "sissy",
    "sissy squat",
    "sit",
    "sit bent",
    "sit bosu",
    "sit straight",
    "sit wall",
    "sit-up",
    "sit-up arms",
    "sit-up male",
    "sitted",
    "sitted alternate",
    "skater",
    "skater hops",
    "ski",
    "ski ergometer",
    "ski step",
    "skier",
    "skin",
    "skin cat",
    "skull",
    "skull crusher",
    "skull press",
    "skullcrusher",
    "slam",
    "slam medicine",
    "sled",
    "sled 45°",
    "sled 45в°",
    "sled calf",
    "sled closer",
    "sled degrees",
    "sled forward",
    "sled hack",
    "sled lying",
    "sled one",
    "sledge",
    "sledge hammer",
    "slide",
    "slingers",
    "slingers hanging",
    "smith",
    "smith back",
    "smith behind",
    "smith bench",
    "smith bent",
    "smith chair",
    "smith close-grip",
    "smith deadlift",
    "smith decline",
    "smith front",
    "smith full",
    "smith hack",
    "smith hip",
    "smith incline",
    "smith leg",
    "smith low",
    "smith machine",
    "smith narrow",
    "smith one",
    "smith rear",
    "smith reverse",
    "smith reverse-grip",
    "smith seated",
    "smith shoulder",
    "smith shrug",
    "smith single",
    "smith sprint",
    "smith squat",
    "smith standing",
    "smith sumo",
    "smith toe",
    "smith upright",
    "smith wide",
    "snatch",
    "snatch pull",
    "speed",
    "speed squat",
    "spell",
    "spell caster",
    "sphinx",
    "spider",
    "spider crawl",
    "spider curl",
    "spine",
    "spine stretch",
    "spine twist",
    "split",
    "split squat",
    "split squats",
    "sprint",
    "sprint lunge",
    "sprints",
    "squad",
    "squad stretch",
    "squat",
    "squat back",
    "squat bosu",
    "squat calf",
    "squat clean",
    "squat jerk",
    "squat jump",
    "squat knees",
    "squat overhead",
    "squat pistol",
    "squat row",
    "squat side",
    "squat style",
    "squat support",
    "squats",
    "squats male",
    "squatting",
    "squatting curl",
    "squatting row",
    "squeeze",
    "stability",
    "stability ball",
    "stability ball,",
    "stabilization",
    "staircase",
    "stalder",
    "stalder press",
    "stance",
    "stance squat",
    "standing",
    "standing alternate",
    "standing alternating",
    "standing archer",
    "standing around",
    "standing back",
    "standing behind",
    "standing bent",
    "standing biceps",
    "standing bradford",
    "standing calf",
    "standing calves",
    "standing chest",
    "standing chin-up",
    "standing close",
    "standing close-grip",
    "standing concentration",
    "standing cross-over",
    "standing crunch",
    "standing curl",
    "standing fly",
    "standing french",
    "standing front",
    "standing hammer",
    "standing hamstring",
    "standing hand",
    "standing hip",
    "standing inner",
    "standing kickback",
    "standing lateral",
    "standing leg",
    "standing lift",
    "standing low",
    "standing military",
    "standing one",
    "standing overhead",
    "standing palms",
    "standing pelvic",
    "standing preacher",
    "standing pull-up",
    "standing pulldown",
    "standing rear",
    "standing reverse",
    "standing rocking",
    "standing rollerout",
    "standing row",
    "standing shoulder",
    "standing single",
    "standing straight",
    "standing triceps",
    "standing twist",
    "standing twisting",
    "standing wheel",
    "standing wide",
    "standing wide-grip",
    "standing zottman",
    "star",
    "star jump",
    "stationary",
    "stationary bike",
    "step",
    "step overhead",
    "step rear",
    "step single",
    "step swing",
    "step-up",
    "step-up lunge",
    "step-up split",
    "stepbox",
    "stepbox support",
    "stepmill",
    "sternum",
    "sternum chin",
    "stiff",
    "stiff leg",
    "stirrups",
    "stork",
    "stork stance",
    "straddle",
    "straddle maltese",
    "straddle planche",
    "straight",
    "straight arm",
    "straight back",
    "straight bar",
    "straight crossovers",
    "straight leg",
    "straight legs",
    "straight twisting",
    "strap",
    "straps",
    "stretch",
    "stretch exercise",
    "stretch hands",
    "stretch lunge",
    "stretch male",
    "stretch pyramid",
    "stretch rope",
    "stretch stability",
    "stretch strap",
    "stride",
    "stride run",
    "style",
    "sumo",
    "sumo deadlift",
    "sumo high",
    "sumo pull",
    "sumo squat",
    "superman",
    "superman push-up",
    "supinated",
    "supinated triceps",
    "supination",
    "supination floor",
    "supine",
    "supine biceps",
    "supine chest",
    "supine curl",
    "supine reverse",
    "supine triceps",
    "supper",
    "supper legs",
    "support",
    "support head",
    "supported",
    "supported squat",
    "suspended",
    "suspended abdominal",
    "suspended push-up",
    "suspended reverse",
    "suspended row",
    "suspended split",
    "svend",
    "svend press",
    "swimmer",
    "swimmer kicks",
    "swing",
    "swing 360",
    "sz-bar",
    "sz-bar arm",
    "t-bar",
    "t-bar reverse",
    "t-bar row",
    "t-raise",
    "tap",
    "tap push-up",
    "tap shoulder",
    "tate",
    "tate press",
    "tennis",
    "tennis ball",
    "thibaudeau",
    "thibaudeau kayak",
    "three",
    "three bench",
    "through",
    "through rope",
    "throw",
    "throw down",
    "thruster",
    "thrusts",
    "thrusts knees",
    "tibialis",
    "tibialis stretch",
    "tilt",
    "tilt into",
    "tire",
    "tire flip",
    "toe",
    "toe pose",
    "toe raise",
    "toe touch",
    "touch",
    "touch crunch",
    "touch male",
    "touchers",
    "towel",
    "towel row",
    "trainer",
    "trap",
    "trap bar",
    "treadmill",
    "tricep",
    "tricep dips",
    "tricep extension",
    "tricep kickback",
    "tricep pushdown",
    "triceps",
    "triceps dip",
    "triceps dips",
    "triceps extension",
    "triceps press",
    "triceps pushdown",
    "triceps stretch",
    "tuck",
    "tuck crunch",
    "tuck reverse",
    "turkish",
    "turkish get",
    "twin",
    "twin handle",
    "twist",
    "twist fly",
    "twist hip",
    "twist legs",
    "twist male",
    "twist row",
    "twist stability",
    "twist toe",
    "twist up-down",
    "twisted",
    "twisted flyes",
    "twisted leg",
    "twisting",
    "twisting bench",
    "twisting chest",
    "twisting crunch",
    "twisting leg",
    "twisting overhead",
    "twisting pull",
    "twisting seated",
    "twisting sit-up",
    "twists",
    "twists stability",
    "two",
    "two arm",
    "two legs",
    "two toe",
    "two-one",
    "two-one leg",
    "under",
    "under both",
    "underhand",
    "underhand pulldown",
    "unilateral",
    "unilateral row",
    "up-down",
    "upper",
    "upper back",
    "upper chest",
    "upper row",
    "upright",
    "upright row",
    "upright shoulder",
    "ups",
    "upward",
    "upward facing",
    "v-bar",
    "v-bar arm",
    "v-sit",
    "v-sit floor",
    "v-up",
    "variation",
    "vertical",
    "vertical bar",
    "vertical leg",
    "vertical pallof",
    "vertical row",
    "w-press",
    "waiter",
    "waiter biceps",
    "walk",
    "walk elliptical",
    "walking",
    "walking high",
    "walking incline",
    "walking lunge",
    "walking stepmill",
    "wall",
    "wall calf",
    "weighted",
    "weighted bench",
    "weighted close",
    "weighted cossack",
    "weighted crunch",
    "weighted decline",
    "weighted donkey",
    "weighted drop",
    "weighted front",
    "weighted hanging",
    "weighted hyperextension",
    "weighted kneeling",
    "weighted lunge",
    "weighted muscle",
    "weighted one",
    "weighted overhead",
    "weighted pull-up",
    "weighted round",
    "weighted russian",
    "weighted seated",
    "weighted side",
    "weighted sissy",
    "weighted squat",
    "weighted standing",
    "weighted straight",
    "weighted stretch",
    "weighted svend",
    "weighted three",
    "weighted tricep",
    "weighted triceps",
    "wheel",
    "wheel rollerout",
    "wheel run",
    "wide",
    "wide angle",
    "wide bench",
    "wide curl",
    "wide grip",
    "wide hand",
    "wide military",
    "wide press",
    "wide pulldown",
    "wide reverse",
    "wide squat",
    "wide-grip",
    "wide-grip chest",
    "wide-grip curl",
    "wide-grip press",
    "wide-grip pullover",
    "wide-grip row",
    "wide-grip upright",
    "wind",
    "wind sprints",
    "windmill",
    "wipers",
    "world",
    "world greatest",
    "wrist",
    "wrist circles",
    "wrist curl",
    "wrist pull",
    "wrist rollerer",
    "y-raise",
    "yoga",
    "yoga pose",
    "zercher",
    "zercher squat",
    "zottman",
    "zottman curl",
    "zottman preacher",
  ];
}
